WITH
  transaction_data AS (
  SELECT
    date,
    EXTRACT(month
    FROM
      date) AS month,
    EXTRACT(year
    FROM
      date) AS year,
    description,
    CASE
      WHEN LOWER(description) LIKE '%kc%market%' THEN 'groceries'
      WHEN LOWER(description) LIKE '%amazon%' THEN 'misc'
      WHEN LOWER(description) LIKE '%gas%' THEN 'car'
      WHEN LOWER(description) LIKE '%yehuda%' THEN 'rent'
      WHEN LOWER(description) LIKE '%publix%' THEN 'groceries'
      WHEN LOWER(description) LIKE '%sushi%' THEN 'resturaunt'
      WHEN LOWER(description) LIKE '%amzn%' THEN 'misc'
      WHEN LOWER(description) LIKE '%east%coast%' THEN 'moving'
      WHEN LOWER(description) LIKE '%leon%' THEN 'car'
      WHEN LOWER(description) LIKE '%steakhouse%' THEN 'resturaunt'
      WHEN LOWER(description) LIKE '%grand cafe%' THEN 'resturaunt'
      WHEN LOWER(description) LIKE '%hatzedaka%' THEN 'tzedaka'
      WHEN LOWER(description) LIKE '%charity%' THEN 'tzedaka'
      WHEN LOWER(description) LIKE '%ambetter%' THEN 'health ins'
      WHEN LOWER(description) LIKE '%grove kosher%' THEN 'groceries'
      WHEN LOWER(description) LIKE '%pizz%' THEN 'resturaunt'
      WHEN LOWER(description) LIKE '%supercuts%' THEN 'haircut'
      WHEN LOWER(description) LIKE '%zelle%kollel%' THEN 'tzedaka'
      WHEN LOWER(description) LIKE '%chesed%' THEN 'tzedaka'
      WHEN LOWER(description) LIKE '%sammys%' THEN 'resturaunt'
      WHEN LOWER(description) LIKE '%webce%' THEN 'misc'
      WHEN LOWER(description) LIKE '%httpsafna%' THEN 'tzedaka'
      WHEN LOWER(description) LIKE '%youtube%' THEN 'subscription'
      WHEN LOWER(description) LIKE '%petrol%' THEN 'car'
      WHEN LOWER(description) LIKE '%save as you go%' THEN 'savings'
      WHEN LOWER(description) LIKE '%chasodim%' THEN 'tzedaka'
      WHEN LOWER(description) LIKE '%kneset mordechai%' THEN 'tzedaka'
      WHEN LOWER(description) LIKE '%yitzy%' THEN 'misc'
      WHEN description LIKE '%CENTRAL TZEDAKA%' THEN 'tzedaka'
      WHEN description LIKE '%RECURRING PAYMENT AUTHORIZED ON 08/22 GOOGLE%' THEN 'subscription'
      WHEN LOWER(description) LIKE '%united%' THEN 'travel'
      WHEN LOWER(description) LIKE '%haagen%' THEN 'resturaunt'
      WHEN description LIKE '*Twitter' THEN 'subscription'
      WHEN description LIKE '%WINN-DIXIE%' THEN 'groceries'
      WHEN LOWER(description) LIKE '%wal%mart%' THEN 'groceries'
      WHEN description LIKE 'ONLINE TRANSFER TO SIMON ' THEN 'savings'
      WHEN description LIKE '%SQ*FRANCIS%' THEN 'tzedaka'
      WHEN description LIKE 'AHAVAS CHESED' THEN 'tzedaka'
      WHEN description LIKE '%LADIES%BIKUR%CHOLI%'THEN 'tzedaka'
      WHEN description LIKE '%VSI*PARKS%' THEN 'outing'
      WHEN LOWER(description) LIKE '%arons%kissena%' THEN 'groceries'
      WHEN LOWER(description) LIKE '%fidelis%' THEN 'health ins'
      WHEN LOWER(description) LIKE '%walgreens%' THEN 'misc'
      WHEN LOWER(description) LIKE 'sunoco' THEN 'car'
      WHEN LOWER(description) LIKE 'verizon' THEN 'wifi'
      WHEN LOWER(description) LIKE '%golan%' THEN 'resturaunt'
      WHEN LOWER(description) LIKE '%chop%chop%' THEN 'resturaunt'
      WHEN LOWER(description) LIKE 'shop smart' THEN 'groceries'
      WHEN LOWER(description) LIKE 'dunkin' THEN 'resturaunt'
      WHEN LOWER(description) LIKE '%exxon%' THEN 'car'
      WHEN LOWER(description) LIKE 'mikail' THEN 'haircut'
      WHEN LOWER(description) LIKE 'photobooth' THEN 'outing'
      WHEN LOWER(description) LIKE 'parking' THEN 'outing'
      WHEN LOWER(description) LIKE 'mikvah' THEN 'misc'
      WHEN LOWER(description) LIKE 'nebel mommy' THEN 'misc'
      WHEN LOWER(description) LIKE '%transfer%' THEN 'transfer'
      WHEN description LIKE '%online transfer to simon d%' THEN 'transfer'
      WHEN description LIKE 'VSI*PARKS' THEN 'outing'
      WHEN description LIKE '%SQ%LAKEWOOD%' THEN 'tzedaka'
      WHEN LOWER(description) LIKE '%francis%' THEN 'tzedaka'
      WHEN LOWER(description) LIKE '%tzedakah%' THEN 'tzedaka'
      WHEN LOWER(description) LIKE '%old navy%' THEN 'misc'
      WHEN LOWER(description) LIKE '%geico%' THEN 'car'
      WHEN description LIKE '%ARIEL%DELICIOUS%' THEN 'resturaunt'
      WHEN description LIKE '%CHASDEI MEIR%' THEN 'tzedaka'
      WHEN description LIKE '%HAROLD WEISSMAN%' THEN 'Doctor'
      WHEN LOWER(description) LIKE '%cafe%' THEN 'resturaunt'
      WHEN LOWER(description) LIKE '%party city%' THEN 'misc'
      WHEN LOWER(description) LIKE '%delta%' THEN 'travel'
      WHEN LOWER(description) LIKE '%cmsvend%' THEN 'resturaunt'
      WHEN description LIKE '%IDEMIA TSA PRECHEC%' THEN 'travel'
      WHEN description LIKE '%7-ELEVEN%' THEN 'resturaunt'
      WHEN description LIKE '%CHINA BISTRO%' THEN 'resturaunt'
      WHEN description LIKE '%SHELL OIL%' THEN 'car'
      WHEN description LIKE '%CVS/PHARMACY%' THEN 'misc'
      WHEN description LIKE '%SHAAREI TZION%' THEN 'tzedaka'
      WHEN description LIKE '%E-Z*PASSNY%' THEN 'car'
      WHEN description LIKE '%MIKAIL%' THEN 'haircut'
      WHEN description LIKE '%SAMMY%' THEN 'resturaunt'
      WHEN description LIKE '%SUNOCO%' THEN 'car'
      WHEN description LIKE '%TCF-TORAS%' THEN 'tzedaka'
      WHEN LOWER(description) LIKE '%rock%roll%' THEN 'resturaunt'
      WHEN LOWER(description) LIKE '%lukoil%' THEN 'car'
      WHEN LOWER(description) LIKE '%segel%' THEN 'bris'
      WHEN LOWER(description) LIKE '%paraking%gara%' THEN 'misc'
      WHEN LOWER(description) LIKE '%mikvah%' THEN 'misc'
      WHEN LOWER(description) LIKE '%nebel%mommy%' THEN 'misc'
      WHEN LOWER(description) LIKE '%verizon%' THEN 'wifi'
      WHEN LOWER(description) LIKE '%nycdot parking%' THEN 'outing'
      WHEN LOWER(description) LIKE '%exxonmobile%' THEN 'car'
      WHEN LOWER(description) LIKE '%dunkin%' THEN 'resturaunt'
      WHEN LOWER(description) LIKE '%shop%smart%' THEN 'groceries'
      WHEN LOWER(description) LIKE '%psy%fid%' THEN 'health ins'
      WHEN LOWER(description) LIKE '%hudson%' THEN 'outing'
      WHEN LOWER(description) LIKE '%meal%mart%' THEN 'groceries'
      WHEN LOWER(description) LIKE '%auto%boss%' THEN 'car'
      WHEN LOWER(description) LIKE '%schreibers%' THEN 'resturaunt'
      WHEN LOWER(description) LIKE '%david%cleaners%' THEN 'misc'
      WHEN LOWER(description) LIKE '%mta%nyct%' THEN 'misc'
      WHEN LOWER(description) LIKE '%pys%fid%' THEN 'health ins'
      WHEN LOWER(description) LIKE '%congregation%ohel%' THEN 'tzedaka'
      WHEN LOWER(description) LIKE '%non%wells%atm%' THEN 'misc'
      WHEN LOWER(description) LIKE '%d%&%j%' THEN 'car'
      WHEN LOWER(description) LIKE '%non-wf%atm%' THEN 'misc'
      WHEN LOWER(description) LIKE '%wealth%of%health%' THEN 'misc'
      WHEN LOWER(description) LIKE '%google%' THEN 'subscription'
      WHEN LOWER(description) LIKE '%american%air%' THEN 'travel'
      WHEN LOWER(description) LIKE '%rite%aid%' THEN 'misc'
      WHEN LOWER(description) LIKE '%photobooth%' THEN 'outing'
      WHEN LOWER(description) LIKE '%parking%' THEN 'outing'
      WHEN LOWER(description) LIKE '%bp%' THEN 'car'
      WHEN LOWER(description) LIKE '%heimish%' THEN 'groceries'
      WHEN LOWER(description) LIKE '%zelle%asadi%' THEN 'misc'
      WHEN LOWER(description) LIKE '%kohl%' THEN 'misc'
      WHEN LOWER(description) LIKE '%venmo%' THEN 'misc'
      WHEN LOWER(description) LIKE '%speedway%' THEN 'car'
      WHEN LOWER(description) LIKE '%autozone%' THEN 'car'
      WHEN LOWER(description) LIKE '%upper%cru%' THEN 'resturaunt'
      WHEN LOWER(description) LIKE '%kosher%bagels%' THEN 'resturaunt'
      WHEN LOWER(description) LIKE '%surgeons%' THEN 'Doctor'
      WHEN LOWER(description) LIKE '%fpl%' THEN 'utilities'
      WHEN LOWER(description) LIKE '%fpl%' THEN 'utilities'
      WHEN LOWER(description) LIKE '%maintenance%fee%' THEN 'misc'
      WHEN LOWER(description) LIKE '%amazing%savings%' THEN 'misc'
      WHEN LOWER(description) LIKE '%yih%' THEN 'misc'
      WHEN LOWER(description) LIKE '%payrange%' THEN 'misc'
      WHEN LOWER(description) LIKE '%target%' THEN 'misc'
      WHEN LOWER(description) LIKE '%chatbooks%' THEN 'misc'
      WHEN LOWER(description) LIKE '%snapfish%' THEN 'misc'
      WHEN LOWER(description) LIKE '%spotify%' THEN 'subscription'
      WHEN LOWER(description) LIKE '%apple%com%' THEN 'subscription'
      WHEN LOWER(description) LIKE '%noom%' THEN 'subscription'
      WHEN LOWER(description) LIKE '%starbucks%' THEN 'resturaunt'
      WHEN LOWER(description) LIKE '%lafamilia%' THEN 'travel'
      WHEN LOWER(description) LIKE '%costco%' THEN 'groceries'
      WHEN LOWER(description) LIKE '%bnai%sephardim%' THEN 'misc'
      WHEN LOWER(description) LIKE '%laboratory%' THEN 'Doctor'
      WHEN LOWER(description) LIKE '%mint%mobile%' THEN 'misc'
      WHEN LOWER(description) LIKE '%zelle%' THEN 'misc'
      WHEN LOWER(description) LIKE '%monthly%service%fee%' THEN 'misc'
      WHEN LOWER(description) LIKE '%simons%active%tr%' THEN 'Active Trade Salary'
      WHEN LOWER(description) LIKE '%h&a%property%payroll%' THEN 'Sarah Salary'
      WHEN LOWER(description) LIKE '%payment%to%daniel%simon%for%invoice%' THEN 'Paypal Art Comm'
    ELSE
    'uncatergorized'
  END
    AS category,
    amount AS amount
  FROM
    spending_history.all_transactions
  ORDER BY
    year DESC,
    month DESC)
SELECT
  *
FROM
  transaction_data
WHERE
  LOWER(category) != 'transfer'
